name: anis_almumin
description: أنيس المؤمن - أوقات الصلاة والأذكار
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.7.0 <4.0.0'
dependencies:
  flutter: {sdk: flutter}
  flutter_localizations: {sdk: flutter}
  flutter_riverpod: ^3.4.3
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  geolocator: ^13.0.1
  geocoding: ^4.0.0
  hijri: ^3.0.0
  intl: any
flutter:
  uses-material-design: true
  assets:
    - assets/adhkar.json
